name: Unit Tests

on:
  - push
  - pull_request

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.julia-arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - '1.0' # LTS
          - '1.6' # LTS
          - '1'
          - 'nightly'
        julia-arch:
            - x64
        os: [ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: Run Tests
        uses: julia-actions/julia-runtest@v1
      - name: Create CodeCov
        uses: julia-actions/julia-processcoverage@v1
      - name: Upload CodeCov
        uses: codecov/codecov-action@v2
        with:
          files: lcov.info
